import brachialismuscle from '../assets/brachialis-muscle.svg'
import hamstring from '../assets/hamstring.svg'
export const parts = [
  {
    id:1,
    name:"腕",
    img:brachialismuscle,
    menus:[
      {
        id:1,
        name:"ダンベルアームカール",
        summary:"上腕筋を鍛える際の王道トレ!!",
        equipment:[1],
        muscles:[1,2,3],
        procedure:[
          "ダンベルを持ちまっすぐ立つ",
          "脇を締めて肘を固定したまま、肘を曲げる",
          "肘が曲がり切ったところで、ゆっくり下ろす"
        ],
        hint:[
          "腰や背中が曲がっていると、上腕二頭筋への負荷が逃げるため注意"
        ]
      },
      {
        id:2,
        name:"バーベルアームカール",
        summary:"上腕筋を鍛える際の王道トレ!!",
        equipment:[1],
        muscles:[1,2,3],
        procedure:[
          "バーベルを持ちまっすぐ立つ",
          "脇を締めて肘を固定したまま、肘を曲げる",
          "肘が曲がり切ったところで、ゆっくり下ろす"
        ],
        hint:[
          "腰や背中が曲がっていると、上腕二頭筋への負荷が逃げるため注意"
        ]
      },
      {
        id:3,
        name:"ハンマーカール",
        summary:"上腕筋を鍛える際の王道トレ!!",
        equipment:[1],
        muscles:[1,2,3],
        procedure:[
          "手のひらが内側を向くようにダンベルを持つ",
          "脇を締めて肘を固定したまま、肘を曲げる",
          "肘が曲がり切ったところで、ゆっくり下ろす"
        ],
        hint:[
          "腰や背中が曲がっていると、上腕二頭筋への負荷が逃げるため注意"
        ]
      }
    ]
  },
  {
    id:2,
    name:"ハムストリングス",
    img:hamstring,
    menus:[
      {
        id:1,
        name:"レッグカール",
        summary:"太もも裏を鍛えられる筋トレ!",
        equipment:[2],
        muscles:[4,5,6],
        procedure:[
          "アームのスタート角度を調整します",
          "膝を2秒かけ曲げる",
          "膝を2秒かけ戻す"
        ],
        hint:[
          "可能な限り反動は使わないようにしましょう"
        ]
      }
    ]
  },
]
export const equipments = [
  {
    id:1,
    name:"ダンベル"
  },
  {
    id:2,
    name:"ラットプルダウン"
  }
]
export const muscles = [
  {
    id:1,
    name:"上腕二頭筋"
  },
  {
    id:2,
    name:"腕橈骨筋"
  },
  {
    id:3,
    name:"上腕筋"
  },
  {
    id:4,
    name:"大腿二頭筋",
  },
  {
    id:5,
    name:"半腱様筋",
  },
  {
    id:6,
    name:"半膜様筋",
  }
]